# Generated by Django 4.1.7 on 2023-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="../static/media/images/% Y/% m/% d/"),
        ),
    ]
