# Generated by Django 4.1.7 on 2023-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Enter a description",
                max_length=2000,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Enter a description",
                max_length=2000,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
